User root
Group root
Port 3128
LogLevel Error
DisableViaHeader yes
ConnectPort 443
ConnectPort 8443
Allow 0.0.0.0/0
Allow ::/0
MaxClients 32
Anonymous "Host"
Anonymous "Authorization"
Anonymous "Cookie"
Anonymous "User-Agent"
Anonymous "Content-Type"
Anonymous "Accept-Encoding"
Anonymous "Range"
Anonymous "Cache-Control"
Anonymous "Content-Length"
Anonymous "Accept-Charset"
