worker_processes auto;
pid /etc/nginx/logs/nginx.pid;
worker_rlimit_nofile 500000;

events {
  worker_connections 100000;
}

http {
  sendfile on;
  tcp_nopush on;
  tcp_nodelay on;
  keepalive_timeout 65;
  types_hash_max_size 2048;
  server_names_hash_bucket_size 128;

  include mime.types;
  default_type application/octet-stream;

  access_log /etc/nginx/logs/access.log combined;
  error_log /etc/nginx/logs/error.log info;

  gzip on;
  gzip_disable "msie6";

  proxy_cache_path /var/www/cache levels=1:2 keys_zone=s3-cache:8m max_size=8000m inactive=720m use_temp_path=off;

  server {
    listen 80;
    server_name $SITE_DOMAIN;

    location / {
      proxy_pass http://caddy:80;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
    }
  }

  server {
    listen 80;
    server_name $CDN_DOMAIN;

    location / {
      proxy_cache s3-cache;
      proxy_cache_valid 200 302 720m;
      proxy_cache_valid 404 1m;
      proxy_cache_use_stale error timeout invalid_header updating http_500 http_502 http_503 http_504;
      proxy_cache_lock on;
      add_header X-Cache-Status $upstream_cache_status;

      proxy_pass http://caddy:80;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
    }
  }

  # server {
  #   listen 80;
  #   server_name $EXT_DOMAIN;
  # 
  #   location / {
  #     proxy_pass http://gocamo:8080;
  #     proxy_set_header Host $host;
  #     proxy_set_header X-Real-IP $remote_addr;
  #     proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  #     proxy_set_header X-Forwarded-Proto $scheme;
  #   }
  # }
}
